
DEFAULT_DATA_DIR = Path("/home/moseslab/denise/embeddings/data_to_embed/")
DEFAULT_RESULT_DIR = Path("/home/moseslab/denise/embeddings/RES/")

ESM_SCRIPT = Path("/home/moseslab/denise/Paper/src/idr_diverge/embed/esm_embed.py")
IDR_LM_SCRIPT = Path("/home/moseslab/denise/Paper/src/idr_diverge/embed/idrlm_embed.py")
BERT_CONFIG = path (for idr_lm)
OUTPUT PATH

TYPE:  #ESM | IDR_LM | IDR_LM_random