inputs:
  dist_matrix: null
  background_emb: /home/moseslab/denise/Paper/data/embed/human_idrs_esm1b.csv #/data/embeddings/human_idr_background.csv
  ortholog_emb: /home/moseslab/denise/embeddings/esm1b/idr_orthologs #/data/embeddings/orthologs/ #file of ortholog embeddings or directory of ortholog embeddings
  homolog_annotation: /home/moseslab/denise/Paper/data/annotations/ensembl_homol_reference_10-10.pkl #/data/annotations/ensembl_homology.pkl
  fam_map: /home/moseslab/denise/Paper/src/distances/current/family_to_genes.json #/home/moseslab/denise/Paper/src/distances/current/fam_to_genes_test.json #Optional but required if random_neighbour_divergence is false
  #Optional inputs:
  #genes: null #list of specific genes to compute divergence for, if null compute for all genes in fam_map FORMAT: gene1,gene2,gene3
  #fam_id: null #specific family to compute divergence for, if null compute for all families in fam_map

outputs:
  out_distance: /home/moseslab/denise/Paper/res/ndist/fam_ndist #directory or specific file to save distance_dict results to
  out_random: /home/moseslab/denise/Paper/res/ndist/rand_ndist/random_bg_distance_matrix.pkl #file to save random background distance matrix to. should be different from fam_distance_matrix output path to avoid confusion
  overwrite: false

compute:
  metric: cosine
  chunk_size: 100
  n_jobs: 6 #split fams into different jobs (or diff segments for within)
  job_id: 3


#Calculate divergence: fam neighbour divergence OR random neighbour divergence

neighbour_divergence:
  dist_type: between      # between | within 
  segment: IDR            #just for naming purposes, not used in code
  return_mode: aggregate  # aggregate | per_gene Only affects within divergence calculation?
  #out_distance: /results/ortholog_divergence/

random_neighbour_divergence:
  enabled: false
  dist_type: within
  segment: IDR  #just for naming purposes, not used in code
  sample_size: 100 #default 100 segments
  random_seed: 42
  return_mode: aggregate
  #out_random: /results/ortholog_divergence/random_bg_distance_matrix.pkl #file to save random background distance matrix to. should be different from fam_distance_matrix output path to avoid confusion
  

ortholog_filter:
  enabled: true
  ortholog_types: ortholog_one2one_one2many
    #- ortholog_one2one
    #- ortholog_one2many
    #-ortholog_one2one_one2many
  min_species_coverage: 0.3
  min_species: 5

run:
  verbose: true

calculate_FND:
  enabled: false
  bg_distance_matrix: null #optional, if not provided will compute within ortholog distances from random background embeddings **FILE PATH
  fam_distance_matrix: null #optional, if not provided will compute distances from ortholog embeddings referenced in fam_map **DIRECTORY PATH
  output_results: /results/ortholog_divergence/FND_results.csv