

##Filter orthologs 

ensembl_homol_ref: /home/moseslab/denise/Paper/data/annotations/ensembl_homol_reference_10-10.pkl
ortholog_type: ortholog_one2one
species_threshold: 0.5
drop_duplicates: percent_id
n_orthologs: 10


human_idr_embed_path: /home/moseslab/denise/Paper/data/embed/human_idrs_esm1b.csv
human_pfam_embed_path: /home/moseslab/denise/Paper/data/embed/human_PFAM_esm_updated.csv
protein_fam_path: /home/moseslab/denise/IDR_LM/data/annotations/hgnc_gene_groups_07_14_25.csv


#Need to edit

cdk_pfam_ortho_embed_path: /home/moseslab/denise/embeddings/esm1b/pfam/CDK_PFAM_ortho_07_31_25_esm.h5

idr_ortho_embed_dir: /home/moseslab/denise/embeddings/esm1b/idr_orthologs


#Annotation paths
#gene_group_path = '/home/moseslab/denise/IDR_LM/data/annotations/hgnc_gene_groups_07_14_25.csv'
#gene_group_df = pd.read_csv('/home/moseslab/denise/IDR_LM/data/annotations/hgnc_gene_groups_07_14_25.csv')

#annot_df = pd.read_table('/home/moseslab/denise/IDR_LM/data/annotations/idr_annotations/uniprotkb_Human_AND_model_organism_9606_2024_08_20.tsv')
#genedict =annot_df.set_index('Entry')['Entry Name'].to_dict()
