
#Fasta or directory of fasta files to embed, directory to write embeddings (h5), and script paths for esm and IDR_LM embedding. Also specify which embedding type to run (esm, IDR_LM, or IDR_LM_random)
data_dir: /home/moseslab/denise/IDR_LM/data/sequences/IDRs/human_idrs/cdk_idrs_human.fasta #/home/moseslab/denise/embeddings/data_to_embed/ #Directory of fasta files to embed
result_dir: ../src/idr_diverge/embed #/home/moseslab/denise/embeddings/RES/ #Directory to write embeddings (h5)

#These are the script paths for esm and IDR_LM embeddings. Should stay the same
esm_script: ../src/idr_diverge/embed/esm_embed.py

#Scripts for IDR_LM embedding. If using IDR_LM_random, still specify the same script paths but the code will ignore the model file and bert config and just randomly initialize the model instead.
idr_lm_script: ../src/idr_diverge/IDR_LM_train/idrlm_embed.py
bert_config: ../src/idr_diverge/IDR_LM_train/bert_config.json #IDR_LM bert config for random initialization only
model_file: /home/moseslab/denise/IDR_LM/src/train/saved_model/best_model_3M_50ep #/home/moseslab/denise/IDR_LM/results/model_checkpoints/1M_8b_100ep-checkpoints/checkpoint-epoch-26/' #model file path for IDR_LM only

#Specify which embedding type to run: esm, IDR_LM, or IDR_LM_random. If using IDR_LM_random, the code will ignore the model file and bert config and just randomly initialize the model instead.
embed_type: IDR_LM #esm  | IDR_LM | IDR_LM_random