inputs:
  dist_matrix: null
  background_emb: ../../../data/human_PFAM_esm_updated.csv #/home/moseslab/denise/Paper/data/embed/human_idrs_esm1b.csv #/data/embeddings/human_idr_background.csv
  ortholog_emb: ../../../data/unrelated_pfam_sample_10_23_25_esm.h5 #/home/moseslab/denise/Paper/data/embed/CDK_PFAM_ortho_07_31_25_esm.csv #/home/moseslab/denise/embeddings/esm1b/idr_orthologs #/data/embeddings/orthologs/ #file of ortholog embeddings or directory of ortholog embeddings
  homolog_annotation: ../../../data/ensembl_homol_reference_10-10.pkl #/data/annotations/ensembl_homology.pkl
  fam_map: rand_genes_pfam.json #/home/moseslab/denise/Paper/src/distances/current/cdk_to_genes.json #/home/moseslab/denise/Paper/src/distances/current/family_to_genes.json #Optional but required if random_neighbour_divergence is false
  #Optional inputs:
  #genes: null #list of specific genes to compute divergence for, if null compute for all genes in fam_map FORMAT: gene1,gene2,gene3
  #fam_id: null #specific family to compute divergence for, if null compute for all families in fam_map

outputs:
  out_distance: ../../../res/ndist/ #/home/moseslab/denise/Paper/res/ndist/rand_ndist/ #/results/fam_divergence/ #directory or specific file to save distance_dict results to
  out_random: /home/moseslab/denise/Paper/res/ndist/rand_ndist/rand_10_pfam_03_24 #/results/random_divergence/random_bg_distance_matrix.pkl #file to save random background distance matrix to. should be different from fam_distance_matrix output path to avoid confusion
  overwrite: false

compute:
  metric: cosine
  chunk_size: 1000 #5000
  n_jobs: 1 #split fams into different jobs (or diff segments for within)


#Calculate divergence: fam neighbour divergence OR random neighbour divergence

neighbour_divergence:
  dist_type: within      # between | within 
  segment: PFAM #IDR            #just for naming purposes, not used in code
  return_mode: aggregate  # aggregate | per_gene Only affects within divergence calculation?
  #out_distance: /results/ortholog_divergence/
  #Put chunk_size and n_jobs here?

random_neighbour_divergence:
  enabled: false
  dist_type: within
  segment: PFAM  #just for naming purposes, not used in code
  sample_size: 2 #100 #default 100 segments
  random_seed: 42
  return_mode: aggregate
  #out_random: /results/ortholog_divergence/random_bg_distance_matrix.pkl #file to save random background distance matrix to. should be different from fam_distance_matrix output path to avoid confusion
  

ortholog_filter:
  enabled: true
  ortholog_types: ortholog_one2one_one2many #- ortholog_one2one | ortholog_one2many | ortholog_one2one_one2many
  min_species_coverage: 0.5
  min_species: 10

run:
  verbose: true #TODO this is not implemented

calculate_FND:
  enabled: false
  bg_distance_matrix: null #optional, if not provided will compute within ortholog distances from random background embeddings **FILE PATH
  fam_distance_matrix: null #optional, if not provided will compute distances from ortholog embeddings referenced in fam_map **DIRECTORY PATH
  output_results: /results/ortholog_divergence/FND_results.csv